apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  # Estas dos url se debe cambiar por la que genere el minikube - por defecto estan 127.0.0.1:puerto
  lb_auth_issuer_uri: "http://172.21.154.72:30961"
  lb_usuarios_uri: "http://172.21.154.72:32440"
  port: "8001"
  db_host: "mysql8:3306"
  db_database: "msvc_usuarios"
  #db_username: "root"
  #db_password: "tarah723"
  curso_url: "msvc-cursos:8002"
  # Adicionar configuraciones al properties principal del micro servicio desde el confimap
  msvc-usuarios.yml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
# Forma para evitar crear varios archivos, se puede tener varias configuraciones en un solo .yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres14:5432"
  db_database: "msvc_cursos"
  #db_username: "postgres"
  #db_password: "tarah723"
  usuario_url: "msvc-usuarios:8001"