apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  db_database: "msvc_usuarios"
  #db_username: "root"
  #db_password: "tarah723"
  curso_url: "msvc-cursos:8002"
# Forma para evitar crear varios archivos, se puede tener varias configuraciones en un solo .yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres14:5432"
  db_database: "msvc_cursos"
  #db_username: "postgres"
  #db_password: "tarah723"
  usuario_url: "msvc-usuarios:8001"