apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: msvc-cursos
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_database
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres14
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    role: postgres
  type: ClusterIP