apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - image: rgmcove/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: msvc-cursos
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db_database
                  name: msvc-cursos
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: db_username
                  name: msvc-cursos
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: msvc-cursos
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  key: usuario_url
                  name: msvc-cursos
