apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv
  storageClassName: standard
  # storageClassName: ""  Aplica para cuando se usa servicio EKS con EFS en aws
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany  Aplica para cuando se usa servicio EKS con EFS en aws con varios nodos
  resources:
    requests:
      storage: 2Gi